/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIndexRouteImport } from './routes/resume/index'
import { Route as ResumesResume_idRouteImport } from './routes/resumes/$resume_id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIndexRoute = ResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResume_idRoute = ResumesResume_idRouteImport.update({
  id: '/resumes/$resume_id',
  path: '/resumes/$resume_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumes/$resume_id': typeof ResumesResume_idRoute
  '/resume/': typeof ResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumes/$resume_id': typeof ResumesResume_idRoute
  '/resume': typeof ResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resumes/$resume_id': typeof ResumesResume_idRoute
  '/resume/': typeof ResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resumes/$resume_id' | '/resume/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resumes/$resume_id' | '/resume'
  id: '__root__' | '/' | '/resumes/$resume_id' | '/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumesResume_idRoute: typeof ResumesResume_idRoute
  ResumeIndexRoute: typeof ResumeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof ResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resume_id': {
      id: '/resumes/$resume_id'
      path: '/resumes/$resume_id'
      fullPath: '/resumes/$resume_id'
      preLoaderRoute: typeof ResumesResume_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumesResume_idRoute: ResumesResume_idRoute,
  ResumeIndexRoute: ResumeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
